os: osx

language: go

go: 
    - "1.10"

before_install:
    - go get github.com/tcnksm/ghr

after_install:
    - ghr  --username baldguysoftware --token $GITHUB_TOKEN --replace $(cat .version) zealot
